<%
  @path = "#{Rubber.root}/config/database.yml"
  shared_dir = "/mnt/tegu-staging/shared/db"

  @post = <<-ENDSCRIPT
    mkdir -p #{shared_dir}
  ENDSCRIPT
%>

<%= Rubber.env %>:
  adapter: mysql2
  encoding: utf8
  database: tegu_<%= Rubber.env %>
  host: mysql-staging.c1kqam8odmp3.us-east-1.rds.amazonaws.com
  port: 3306
  username: fauna
  password: social40
  reconnect: true