# cloudinary login: sanjay+teamtegu@jarna.com
---
development:
  cloud_name: tegu
  api_key: '572228335418156'
  api_secret: dRLXZPoVLjY1ZhNOxuXGMAWRpKE
  enhance_image_tag: true
  static_image_support: false
  secure: true
test:
  cloud_name: tegu
  api_key: '572228335418156'
  api_secret: dRLXZPoVLjY1ZhNOxuXGMAWRpKE
  enhance_image_tag: true
  static_image_support: false
  secure: true
staging:
  cloud_name: tegu
  api_key: '572228335418156'
  api_secret: dRLXZPoVLjY1ZhNOxuXGMAWRpKE
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: tegu
  api_key: '572228335418156'
  api_secret: dRLXZPoVLjY1ZhNOxuXGMAWRpKE
  enhance_image_tag: true
  static_image_support: false
  secure: true
