---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: stageapp1
  domain: tegu.com
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: unicorn
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: sqlite
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: elasticsearch
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-5eff9b75
  image_type: m3.medium
  image_id: ami-4a0df923
  security_groups:
  - default
  external_host: ec2-54-84-183-54.compute-1.amazonaws.com
  external_ip: 54.84.183.54
  internal_host: ip-172-31-27-195.ec2.internal
  internal_ip: 172.31.27.195
  zone: us-east-1c
  provider: aws
  platform: linux
  root_device_type: ebs
- volumes: {}
  static_ips: {}
